name: auto-update
on:
  push:
    branches:
      - develop
jobs:
  autoupdate:
    name: auto-update
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.NETCODE_CI_SERVICE_TOKEN }}"
          PR_FILTER: "auto_merge"
          PR_READY_STATE: "ready_for_review"
          MERGE_CONFLICT_ACTION: "ignore"

